apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-demo-pod
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
      args:
        - |
          echo "Created at: $(date -u)" > /data/message.txt
          echo "Message saved:"
          cat /data/message.txt
          sleep 3600
      volumeMounts:
        - name: temporary-storage
          mountPath: /data

  volumes:
    - name: temporary-storage
      emptyDir: {}

  restartPolicy: Never