apiVersion: v1
kind: Pod
metadata: 
  name: empty-dir
spec:
  containers:
  - name: empty-dir
    image: busybox:latest
    command: ["/bin/sh","-c",'echo "TimeStamp : $(date)" >> /data/message.txt; sleep 3000']
    volumeMounts:
    - name: empty-vol
      mountPath: /data
  volumes:
    - name: empty-vol
      emptyDir: {}
