apiVersion: v1
kind: Pod
metadata:
  name: day57-resource-pod
  namespace: default
  labels:
    app: day57-resource-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - name: http
          containerPort: 80

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
